### ISSUE TITLE
Loss function

### ISSUE THREAD

**Issue by GritYu** [shaoyanpan/Synthetic-CT-generation-from-MRI-using-3D-transformer-based-denoising-diffusion-model#5]
Hi Shaoyan, 

1. I notice that you used MAE as the loss function for predicting mean. Why didn't you use MSE or CE? Have you ever tried them? 

2. In your 2D project, you kept predict_xstart = False, but you changed it to True in your 3D model #3 . Could you share your thoughts on this change?

I'm greatly looking forward to your reply!

**Comment by shaoyanpan** [comment]
For the loss functions, MSE gives smoother images but should slightly better quantative result. Havn't try CE yet.

For image creation, predict_xstart =False to predict noise is better, give better diversity. For image-to-image translation, predict_xstart =Trueto predict x_0, give better image accuracy and stability. But, lower diversity, which is good because translation should not have diversity.

**Comment by GritYu** [comment]
> For the loss functions, MSE gives smoother images but should slightly better quantative result. Havn't try CE yet.
> 
> For image creation, predict_xstart =False to predict noise is better, give better diversity. For image-to-image translation, predict_xstart =True to predict x_0, give better image accuracy and stability. But, lower diversity, which is good because translation should not have diversity.

Thank you so much! It's really helpful!
